"""Auto-generated Release Manager skill pack scaffold.

Generated by scripts/scaffold_agent.py.
"""

from __future__ import annotations

from typing import Any

from aspire_orchestrator.config.templates.skillpack_template import AgenticSkillPack
from aspire_orchestrator.services.agent_sdk_base import AgentContext, AgentResult


class ReleaseManagerSkillPack(AgenticSkillPack):
    """Starter scaffold for Release Manager."""

    def __init__(self) -> None:
        super().__init__(
            agent_id="release_manager",
            agent_name="Release Manager",
            default_risk_tier="yellow",
            memory_enabled=True,
        )

    async def dispatch_action(self, action: str, params: dict[str, Any], ctx: AgentContext) -> AgentResult:
        handlers = {
            "release.checklist.enforce": self.release_checklist_enforce,
            "release.pipeline.track": self.release_pipeline_track,
            "release.notes.generate": self.release_notes_generate,
            "release.deploy.prepare": self.release_deploy_prepare,
        }
        handler = handlers.get(action)
        if handler is None:
            receipt = self.build_receipt(
                ctx=ctx,
                event_type="skillpack.dispatch",
                status="denied",
                inputs={"action": action},
                metadata={"error": "unsupported_action"},
            )
            receipt["policy"] = {"decision": "deny", "reasons": ["UNSUPPORTED_ACTION"]}
            await self.emit_receipt(receipt)
            return AgentResult(success=False, receipt=receipt, error=f"Unsupported action: {action}")
        return await handler(params, ctx)

    async def _handle_read_action(
        self,
        *,
        action: str,
        params: dict[str, Any],
        ctx: AgentContext,
        required_key: str,
    ) -> AgentResult:
        value = str(params.get(required_key, "")).strip()
        if not value:
            receipt = self.build_receipt(
                ctx=ctx,
                event_type=action,
                status="denied",
                inputs={"action": action},
            )
            receipt["policy"] = {"decision": "deny", "reasons": ["MISSING_REQUIRED_FIELD"]}
            await self.emit_receipt(receipt)
            return AgentResult(success=False, receipt=receipt, error=f"Missing {required_key}")

        return await self.execute_with_llm(
            prompt=(
                f"You are {self.agent_name}. Handle the read-only action '{action}'.\n\n"
                f"Request: {value}\n\n"
                "Provide a concise, useful answer and clearly flag any assumptions."
            ),
            ctx=ctx,
            event_type=action,
            step_type="draft",
            inputs={"action": action, required_key: value},
        )

    async def _handle_write_action(
        self,
        *,
        action: str,
        params: dict[str, Any],
        ctx: AgentContext,
        required_key: str,
    ) -> AgentResult:
        value = str(params.get(required_key, "")).strip()
        if not value:
            receipt = self.build_receipt(
                ctx=ctx,
                event_type=action,
                status="denied",
                inputs={"action": action},
            )
            receipt["policy"] = {"decision": "deny", "reasons": ["MISSING_REQUIRED_FIELD"]}
            await self.emit_receipt(receipt)
            return AgentResult(success=False, receipt=receipt, error=f"Missing {required_key}")

        result = await self.execute_with_llm(
            prompt=(
                f"You are {self.agent_name}. Prepare the governed output for '{action}'.\n\n"
                f"Request: {value}\n\n"
                "Return the proposed action, any assumptions, and the next approval-safe step."
            ),
            ctx=ctx,
            event_type=action,
            step_type="draft",
            inputs={"action": action, required_key: value},
        )
        if result.success and self._memory_enabled:
            await self.remember(
                key="release_last_request",
                value=value,
                ctx=ctx,
                fact_type="workflow",
                confidence=0.7,
            )
        return result

    async def release_checklist_enforce(self, params: dict[str, Any], ctx: AgentContext) -> AgentResult:
        """Handle `release.checklist.enforce` requests."""
        return await self._handle_write_action(
            action="release.checklist.enforce",
            params=params,
            ctx=ctx,
            required_key="request",
        )

    async def release_pipeline_track(self, params: dict[str, Any], ctx: AgentContext) -> AgentResult:
        """Handle `release.pipeline.track` requests."""
        return await self._handle_write_action(
            action="release.pipeline.track",
            params=params,
            ctx=ctx,
            required_key="request",
        )

    async def release_notes_generate(self, params: dict[str, Any], ctx: AgentContext) -> AgentResult:
        """Handle `release.notes.generate` requests."""
        return await self._handle_write_action(
            action="release.notes.generate",
            params=params,
            ctx=ctx,
            required_key="request",
        )

    async def release_deploy_prepare(self, params: dict[str, Any], ctx: AgentContext) -> AgentResult:
        """Handle `release.deploy.prepare` requests."""
        return await self._handle_write_action(
            action="release.deploy.prepare",
            params=params,
            ctx=ctx,
            required_key="request",
        )

