"""Auto-generated Security Review skill pack scaffold.

Generated by scripts/scaffold_agent.py.
"""

from __future__ import annotations

from typing import Any

from aspire_orchestrator.config.templates.skillpack_template import AgenticSkillPack
from aspire_orchestrator.services.agent_sdk_base import AgentContext, AgentResult


class SecurityReviewSkillPack(AgenticSkillPack):
    """Starter scaffold for Security Review."""

    def __init__(self) -> None:
        super().__init__(
            agent_id="security_review",
            agent_name="Security Review",
            default_risk_tier="red",
            memory_enabled=True,
        )

    async def dispatch_action(self, action: str, params: dict[str, Any], ctx: AgentContext) -> AgentResult:
        handlers = {
            "security.scan.execute": self.security_scan_execute,
            "security.report.generate": self.security_report_generate,
            "security.violation.flag": self.security_violation_flag,
            "security.review.request": self.security_review_request,
        }
        handler = handlers.get(action)
        if handler is None:
            receipt = self.build_receipt(
                ctx=ctx,
                event_type="skillpack.dispatch",
                status="denied",
                inputs={"action": action},
                metadata={"error": "unsupported_action"},
            )
            receipt["policy"] = {"decision": "deny", "reasons": ["UNSUPPORTED_ACTION"]}
            await self.emit_receipt(receipt)
            return AgentResult(success=False, receipt=receipt, error=f"Unsupported action: {action}")
        return await handler(params, ctx)

    async def _handle_read_action(
        self,
        *,
        action: str,
        params: dict[str, Any],
        ctx: AgentContext,
        required_key: str,
    ) -> AgentResult:
        value = str(params.get(required_key, "")).strip()
        if not value:
            receipt = self.build_receipt(
                ctx=ctx,
                event_type=action,
                status="denied",
                inputs={"action": action},
            )
            receipt["policy"] = {"decision": "deny", "reasons": ["MISSING_REQUIRED_FIELD"]}
            await self.emit_receipt(receipt)
            return AgentResult(success=False, receipt=receipt, error=f"Missing {required_key}")

        return await self.execute_with_llm(
            prompt=(
                f"You are {self.agent_name}. Handle the read-only action '{action}'.\n\n"
                f"Request: {value}\n\n"
                "Provide a concise, useful answer and clearly flag any assumptions."
            ),
            ctx=ctx,
            event_type=action,
            step_type="draft",
            inputs={"action": action, required_key: value},
        )

    async def _handle_write_action(
        self,
        *,
        action: str,
        params: dict[str, Any],
        ctx: AgentContext,
        required_key: str,
    ) -> AgentResult:
        value = str(params.get(required_key, "")).strip()
        if not value:
            receipt = self.build_receipt(
                ctx=ctx,
                event_type=action,
                status="denied",
                inputs={"action": action},
            )
            receipt["policy"] = {"decision": "deny", "reasons": ["MISSING_REQUIRED_FIELD"]}
            await self.emit_receipt(receipt)
            return AgentResult(success=False, receipt=receipt, error=f"Missing {required_key}")

        result = await self.execute_with_llm(
            prompt=(
                f"You are {self.agent_name}. Prepare the governed output for '{action}'.\n\n"
                f"Request: {value}\n\n"
                "Return the proposed action, any assumptions, and the next approval-safe step."
            ),
            ctx=ctx,
            event_type=action,
            step_type="draft",
            inputs={"action": action, required_key: value},
        )
        if result.success and self._memory_enabled:
            await self.remember(
                key="security_last_request",
                value=value,
                ctx=ctx,
                fact_type="workflow",
                confidence=0.7,
            )
        return result

    async def security_scan_execute(self, params: dict[str, Any], ctx: AgentContext) -> AgentResult:
        """Handle `security.scan.execute` requests."""
        return await self._handle_write_action(
            action="security.scan.execute",
            params=params,
            ctx=ctx,
            required_key="request",
        )

    async def security_report_generate(self, params: dict[str, Any], ctx: AgentContext) -> AgentResult:
        """Handle `security.report.generate` requests."""
        return await self._handle_write_action(
            action="security.report.generate",
            params=params,
            ctx=ctx,
            required_key="request",
        )

    async def security_violation_flag(self, params: dict[str, Any], ctx: AgentContext) -> AgentResult:
        """Handle `security.violation.flag` requests."""
        return await self._handle_write_action(
            action="security.violation.flag",
            params=params,
            ctx=ctx,
            required_key="request",
        )

    async def security_review_request(self, params: dict[str, Any], ctx: AgentContext) -> AgentResult:
        """Handle `security.review.request` requests."""
        return await self._handle_write_action(
            action="security.review.request",
            params=params,
            ctx=ctx,
            required_key="request",
        )

