"""Auto-generated SRE Triage skill pack scaffold.

Generated by scripts/scaffold_agent.py.
"""

from __future__ import annotations

from typing import Any

from aspire_orchestrator.config.templates.skillpack_template import AgenticSkillPack
from aspire_orchestrator.services.agent_sdk_base import AgentContext, AgentResult


class SreTriageSkillPack(AgenticSkillPack):
    """Starter scaffold for SRE Triage."""

    def __init__(self) -> None:
        super().__init__(
            agent_id="sre_triage",
            agent_name="SRE Triage",
            default_risk_tier="yellow",
            memory_enabled=True,
        )

    async def dispatch_action(self, action: str, params: dict[str, Any], ctx: AgentContext) -> AgentResult:
        handlers = {
            "sre.alert.detect": self.sre_alert_detect,
            "sre.incident.triage": self.sre_incident_triage,
            "sre.incident.route": self.sre_incident_route,
            "sre.report.generate": self.sre_report_generate,
        }
        handler = handlers.get(action)
        if handler is None:
            receipt = self.build_receipt(
                ctx=ctx,
                event_type="skillpack.dispatch",
                status="denied",
                inputs={"action": action},
                metadata={"error": "unsupported_action"},
            )
            receipt["policy"] = {"decision": "deny", "reasons": ["UNSUPPORTED_ACTION"]}
            await self.emit_receipt(receipt)
            return AgentResult(success=False, receipt=receipt, error=f"Unsupported action: {action}")
        return await handler(params, ctx)

    async def _handle_read_action(
        self,
        *,
        action: str,
        params: dict[str, Any],
        ctx: AgentContext,
        required_key: str,
    ) -> AgentResult:
        value = str(params.get(required_key, "")).strip()
        if not value:
            receipt = self.build_receipt(
                ctx=ctx,
                event_type=action,
                status="denied",
                inputs={"action": action},
            )
            receipt["policy"] = {"decision": "deny", "reasons": ["MISSING_REQUIRED_FIELD"]}
            await self.emit_receipt(receipt)
            return AgentResult(success=False, receipt=receipt, error=f"Missing {required_key}")

        return await self.execute_with_llm(
            prompt=(
                f"You are {self.agent_name}. Handle the read-only action '{action}'.\n\n"
                f"Request: {value}\n\n"
                "Provide a concise, useful answer and clearly flag any assumptions."
            ),
            ctx=ctx,
            event_type=action,
            step_type="draft",
            inputs={"action": action, required_key: value},
        )

    async def _handle_write_action(
        self,
        *,
        action: str,
        params: dict[str, Any],
        ctx: AgentContext,
        required_key: str,
    ) -> AgentResult:
        value = str(params.get(required_key, "")).strip()
        if not value:
            receipt = self.build_receipt(
                ctx=ctx,
                event_type=action,
                status="denied",
                inputs={"action": action},
            )
            receipt["policy"] = {"decision": "deny", "reasons": ["MISSING_REQUIRED_FIELD"]}
            await self.emit_receipt(receipt)
            return AgentResult(success=False, receipt=receipt, error=f"Missing {required_key}")

        result = await self.execute_with_llm(
            prompt=(
                f"You are {self.agent_name}. Prepare the governed output for '{action}'.\n\n"
                f"Request: {value}\n\n"
                "Return the proposed action, any assumptions, and the next approval-safe step."
            ),
            ctx=ctx,
            event_type=action,
            step_type="draft",
            inputs={"action": action, required_key: value},
        )
        if result.success and self._memory_enabled:
            await self.remember(
                key="sre_last_request",
                value=value,
                ctx=ctx,
                fact_type="workflow",
                confidence=0.7,
            )
        return result

    async def sre_alert_detect(self, params: dict[str, Any], ctx: AgentContext) -> AgentResult:
        """Handle `sre.alert.detect` requests."""
        return await self._handle_write_action(
            action="sre.alert.detect",
            params=params,
            ctx=ctx,
            required_key="request",
        )

    async def sre_incident_triage(self, params: dict[str, Any], ctx: AgentContext) -> AgentResult:
        """Handle `sre.incident.triage` requests."""
        return await self._handle_write_action(
            action="sre.incident.triage",
            params=params,
            ctx=ctx,
            required_key="request",
        )

    async def sre_incident_route(self, params: dict[str, Any], ctx: AgentContext) -> AgentResult:
        """Handle `sre.incident.route` requests."""
        return await self._handle_write_action(
            action="sre.incident.route",
            params=params,
            ctx=ctx,
            required_key="request",
        )

    async def sre_report_generate(self, params: dict[str, Any], ctx: AgentContext) -> AgentResult:
        """Handle `sre.report.generate` requests."""
        return await self._handle_write_action(
            action="sre.report.generate",
            params=params,
            ctx=ctx,
            required_key="request",
        )

