-- =============================================================================
-- Migration 097: Memory Spine — Link Tables and Event Inbox
-- =============================================================================
-- Creates four supporting tables for the Office Memory Engine:
--
--   1. public.proactive_candidates — surface-level action suggestions from agents
--   2. public.approval_links       — joins approval_requests to memory + candidates
--   3. public.receipt_memory_links — joins receipts to memory objects
--   4. public.memory_event_inbox   — append-only event intake queue (30-day TTL)
--
-- Also adds a TRIGGER on memory_objects (AFTER INSERT) to maintain the
-- threads.latest_memory_id and threads.last_activity_at denormalized caches.
--
-- Aspire Laws enforced:
--   Law #2 (Receipt for All)  — receipt_memory_links is append-only; no DELETE
--   Law #3 (Fail Closed)      — RLS denies by default; explicit grants only
--   Law #6 (Tenant Isolation) — all tables: tenant_id + suite_id, FORCE RLS
--   Law #9 (Security)         — inbox dedup via idempotency_key; dead-letter on failure
--
-- FK notes (critical):
--   approval_requests.approval_id is TEXT PRIMARY KEY (trust_spine_bundle schema)
--   receipts.receipt_id is TEXT PRIMARY KEY (trust_spine_bundle schema)
--   threads.thread_id is UUID (migration 095)
--   memory_objects.memory_id is UUID (migration 096)
--
-- References:
--   02_SHARED_SCHEMAS.md §2.2, §2.5, §2.6, §2.7
--   03_THREAD_REGISTRY_AND_MEMORY_MODEL.md §3.5 (latest brief caches)
-- =============================================================================

-- =============================================================================
-- TABLE: public.proactive_candidates
-- =============================================================================
-- Surface-level action suggestions generated by agents during session processing.
-- The orchestrator reads these to decide whether to route, draft, or request approval.
-- Dedup key: one open/snoozed candidate per (tenant, suite, office, owner_agent,
--            entity, recommended_action) at a time.

CREATE TABLE IF NOT EXISTS public.proactive_candidates (
    -- Primary key
    candidate_id    UUID    PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Schema versioning
    schema_version  TEXT    NOT NULL DEFAULT 'v1',

    -- Tenant / suite / office scope (Law #6)
    tenant_id       UUID    NOT NULL,
    suite_id        UUID    NOT NULL,
    office_id       UUID    NOT NULL,

    -- Owning agent
    owner_agent     TEXT    NOT NULL CHECK (owner_agent IN (
                                'ava', 'sarah', 'eli', 'nora', 'finn', 'tim', 'system'
                            )),

    -- Source event / memory references
    source_event_ids    UUID[]  NOT NULL DEFAULT '{}',
    source_memory_ids   UUID[]  NOT NULL DEFAULT '{}',

    -- Entity / thread linkage
    entity_type     TEXT    NULL,
    entity_id       UUID    NULL,
    thread_id       UUID    NULL REFERENCES public.threads(thread_id) ON DELETE SET NULL,

    -- Recommendation
    recommended_action  TEXT    NOT NULL CHECK (recommended_action IN (
                                    'create_draft',
                                    'queue_callback',
                                    'request_approval',
                                    'route_to_agent',
                                    'queue_workflow_trigger',
                                    'surface_warning',
                                    'create_internal_task',
                                    'schedule_outbound_voice',
                                    'none'
                                )),
    action_class        TEXT    NOT NULL CHECK (action_class IN (
                                    'internal_only',
                                    'draft',
                                    'approval_request',
                                    'outbound',
                                    'workflow'
                                )),

    -- Reasoning
    why_now         TEXT    NOT NULL,
    confidence      FLOAT   NOT NULL CHECK (confidence >= 0 AND confidence <= 1),

    -- Governance classification
    risk_tier       TEXT    NOT NULL CHECK (risk_tier IN ('green', 'yellow', 'red')),
    needs_approval  BOOLEAN NOT NULL DEFAULT false,
    receipt_required BOOLEAN NOT NULL DEFAULT false,

    -- Scheduling
    due_at          TIMESTAMPTZ NULL,
    cooldown_until  TIMESTAMPTZ NULL,

    -- Lifecycle status
    status          TEXT    NOT NULL DEFAULT 'open'
                        CHECK (status IN (
                            'open', 'snoozed', 'approved', 'executed', 'dismissed', 'expired'
                        )),

    -- Timestamps
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_activity_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.proactive_candidates IS
    'Surface-level action suggestions generated by agents. '
    'Orchestrator consumes these to route, draft, or request approvals. '
    'Dedup: one open/snoozed row per (tenant, suite, office, owner_agent, entity, action). '
    'RLS: tenant_id + suite_id + office_id scoped (Law #6).';

-- Dedup: only one active recommendation per context (prevents duplicate nudges)
CREATE UNIQUE INDEX IF NOT EXISTS uq_proactive_candidates_active
    ON public.proactive_candidates (
        tenant_id, suite_id, office_id, owner_agent,
        entity_type, entity_id, recommended_action
    )
    WHERE status IN ('open', 'snoozed');

-- Workqueue scan: pending candidates ordered by due_at
CREATE INDEX IF NOT EXISTS idx_proactive_candidates_queue
    ON public.proactive_candidates (tenant_id, suite_id, status, due_at ASC NULLS LAST)
    WHERE status IN ('open', 'snoozed');

-- Thread linkage
CREATE INDEX IF NOT EXISTS idx_proactive_candidates_thread
    ON public.proactive_candidates (thread_id, last_activity_at DESC)
    WHERE thread_id IS NOT NULL;

-- Touch trigger (maintain last_activity_at)
CREATE OR REPLACE FUNCTION public.trg_proactive_candidates_touch()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.last_activity_at := now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_proactive_candidates_touch ON public.proactive_candidates;
CREATE TRIGGER trg_proactive_candidates_touch
    BEFORE INSERT OR UPDATE ON public.proactive_candidates
    FOR EACH ROW EXECUTE FUNCTION public.trg_proactive_candidates_touch();

-- RLS
ALTER TABLE public.proactive_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proactive_candidates FORCE ROW LEVEL SECURITY;

CREATE POLICY proactive_candidates_select_tenant ON public.proactive_candidates
    FOR SELECT TO authenticated
    USING (app.is_member(tenant_id::text));

CREATE POLICY proactive_candidates_all_service_role ON public.proactive_candidates
    FOR ALL TO service_role
    USING (true) WITH CHECK (true);

CREATE POLICY proactive_candidates_insert_tenant ON public.proactive_candidates
    FOR INSERT TO authenticated
    WITH CHECK (
        tenant_id::text IN (
            SELECT tm.tenant_id FROM public.tenant_memberships tm
            WHERE tm.user_id = auth.uid()
        )
        AND suite_id = public.current_suite_id()
    );

CREATE POLICY proactive_candidates_update_tenant ON public.proactive_candidates
    FOR UPDATE TO authenticated
    USING (app.is_member(tenant_id::text))
    WITH CHECK (
        tenant_id::text IN (
            SELECT tm.tenant_id FROM public.tenant_memberships tm
            WHERE tm.user_id = auth.uid()
        )
    );

GRANT SELECT, INSERT, UPDATE ON public.proactive_candidates TO authenticated;
GRANT ALL ON public.proactive_candidates TO service_role;


-- =============================================================================
-- TABLE: public.approval_links
-- =============================================================================
-- Joins approval_requests (trust_spine_bundle TEXT PK) to memory objects
-- and proactive candidates. One row per approval — UNIQUE (approval_id).

CREATE TABLE IF NOT EXISTS public.approval_links (
    approval_link_id    UUID    PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Tenant / suite scope (Law #6) — mirrors approval_requests tenant scoping
    tenant_id           UUID    NOT NULL,
    suite_id            UUID    NOT NULL,

    -- FK to approval_requests (TEXT PK per trust_spine_bundle)
    approval_id         TEXT    NOT NULL
                            REFERENCES public.approval_requests(approval_id)
                            ON DELETE CASCADE,

    -- Linked candidate (optional — approval may be system-initiated)
    linked_candidate_id UUID    NULL
                            REFERENCES public.proactive_candidates(candidate_id)
                            ON DELETE SET NULL,

    -- Memory objects that provided context for this approval
    linked_memory_ids   UUID[]  NOT NULL DEFAULT '{}',

    -- Workflow run that this approval gates (optional)
    linked_workflow_run_id  UUID    NULL,

    -- Requesting agent
    requested_by_agent  TEXT    NOT NULL CHECK (requested_by_agent IN (
                                    'ava', 'sarah', 'eli', 'nora', 'finn', 'tim', 'system'
                                )),

    -- Approval outcome fields (denormalized for fast agent reads)
    approval_status     TEXT    NOT NULL DEFAULT 'pending'
                            CHECK (approval_status IN (
                                'pending', 'approved', 'rejected', 'expired'
                            )),

    requested_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    decided_at          TIMESTAMPTZ NULL,
    approver_actor_id   UUID        NULL,
    reason              TEXT        NULL,

    -- Audit
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- One link per approval request
    CONSTRAINT uq_approval_links_approval_id UNIQUE (approval_id)
);

COMMENT ON TABLE public.approval_links IS
    'Joins approval_requests (TEXT PK) to memory objects and proactive candidates. '
    'One row per approval — UNIQUE (approval_id). '
    'RLS: tenant_id + suite_id scoped (Law #6).';

CREATE INDEX IF NOT EXISTS idx_approval_links_tenant
    ON public.approval_links (tenant_id, suite_id, approval_status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_approval_links_candidate
    ON public.approval_links (linked_candidate_id)
    WHERE linked_candidate_id IS NOT NULL;

-- RLS
ALTER TABLE public.approval_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.approval_links FORCE ROW LEVEL SECURITY;

CREATE POLICY approval_links_select_tenant ON public.approval_links
    FOR SELECT TO authenticated
    USING (app.is_member(tenant_id::text));

CREATE POLICY approval_links_all_service_role ON public.approval_links
    FOR ALL TO service_role
    USING (true) WITH CHECK (true);

CREATE POLICY approval_links_insert_tenant ON public.approval_links
    FOR INSERT TO authenticated
    WITH CHECK (
        tenant_id::text IN (
            SELECT tm.tenant_id FROM public.tenant_memberships tm
            WHERE tm.user_id = auth.uid()
        )
        AND suite_id = public.current_suite_id()
    );

-- UPDATE allowed for status transitions (pending → approved/rejected/expired)
CREATE POLICY approval_links_update_tenant ON public.approval_links
    FOR UPDATE TO authenticated
    USING (app.is_member(tenant_id::text))
    WITH CHECK (
        tenant_id::text IN (
            SELECT tm.tenant_id FROM public.tenant_memberships tm
            WHERE tm.user_id = auth.uid()
        )
    );

GRANT SELECT, INSERT, UPDATE ON public.approval_links TO authenticated;
GRANT ALL ON public.approval_links TO service_role;


-- =============================================================================
-- TABLE: public.receipt_memory_links
-- =============================================================================
-- Append-only join table between receipts (TEXT PK) and memory_objects (UUID PK).
-- No UPDATE, no DELETE — a link is immutable once created (Law #2).
-- The composite PK (receipt_id, memory_id) ensures no duplicate links.

CREATE TABLE IF NOT EXISTS public.receipt_memory_links (
    -- Composite primary key prevents duplicate links
    receipt_id      TEXT    NOT NULL
                        REFERENCES public.receipts(receipt_id)
                        ON DELETE CASCADE,
    memory_id       UUID    NOT NULL
                        REFERENCES public.memory_objects(memory_id)
                        ON DELETE CASCADE,

    -- How this link was established (e.g. 'direct', 'inferred', 'workflow')
    linked_via      TEXT    NULL,

    -- Tenant scope for RLS (denormalized from receipts)
    tenant_id       UUID    NOT NULL,
    suite_id        UUID    NOT NULL,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (receipt_id, memory_id)
);

COMMENT ON TABLE public.receipt_memory_links IS
    'Append-only join table between receipts and memory_objects. '
    'Immutable once created — no UPDATE or DELETE. '
    'Composite PK (receipt_id, memory_id) prevents duplicate links. '
    'RLS: tenant_id + suite_id scoped (Law #6).';

CREATE INDEX IF NOT EXISTS idx_receipt_memory_links_memory
    ON public.receipt_memory_links (memory_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_receipt_memory_links_receipt
    ON public.receipt_memory_links (receipt_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_receipt_memory_links_tenant
    ON public.receipt_memory_links (tenant_id, suite_id, created_at DESC);

-- RLS: append-only (SELECT + INSERT only; no UPDATE/DELETE policy = deny)
ALTER TABLE public.receipt_memory_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipt_memory_links FORCE ROW LEVEL SECURITY;

CREATE POLICY receipt_memory_links_select_tenant ON public.receipt_memory_links
    FOR SELECT TO authenticated
    USING (app.is_member(tenant_id::text));

CREATE POLICY receipt_memory_links_all_service_role ON public.receipt_memory_links
    FOR ALL TO service_role
    USING (true) WITH CHECK (true);

CREATE POLICY receipt_memory_links_insert_tenant ON public.receipt_memory_links
    FOR INSERT TO authenticated
    WITH CHECK (
        tenant_id::text IN (
            SELECT tm.tenant_id FROM public.tenant_memberships tm
            WHERE tm.user_id = auth.uid()
        )
        AND suite_id = public.current_suite_id()
    );

-- No UPDATE or DELETE policy — default deny under FORCE RLS (Law #2 append-only)

GRANT SELECT, INSERT ON public.receipt_memory_links TO authenticated;
GRANT ALL ON public.receipt_memory_links TO service_role;


-- =============================================================================
-- TABLE: public.memory_event_inbox
-- =============================================================================
-- Append-only intake queue for MemoryEventEnvelope payloads. Events land here
-- first; the memory pipeline worker processes them into memory_objects and
-- proactive_candidates. 30-day TTL enforced via pg_cron (see cron setup below).
--
-- Status lifecycle: pending → processing → processed | dead_letter
-- Dead-lettered events are retained for forensics and replay.

CREATE TABLE IF NOT EXISTS public.memory_event_inbox (
    -- Primary key
    event_id        UUID    PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Schema versioning
    schema_version  TEXT    NOT NULL DEFAULT 'v1',

    -- Tenant / suite / office scope (Law #6)
    tenant_id       UUID    NOT NULL,
    suite_id        UUID    NOT NULL,
    office_id       UUID    NOT NULL,

    -- Scope extensions (from ScopedIdentity)
    actor_id        UUID    NULL,
    user_id         UUID    NULL,

    -- Event classification
    event_type      TEXT    NOT NULL,

    -- Provenance (from MemoryEventEnvelope)
    source_surface  TEXT    NULL CHECK (source_surface IS NULL OR source_surface IN (
                                'ava_voice', 'sarah_voice', 'eli_inbox', 'nora_meeting',
                                'finn_finance', 'tim_service_lab', 'estimate_studio',
                                'canvas_desk', 'receipt_ledger', 'approval_queue', 'system'
                            )),
    source_agent    TEXT    NULL CHECK (source_agent IS NULL OR source_agent IN (
                                'ava', 'sarah', 'eli', 'nora', 'finn', 'tim', 'system'
                            )),
    runtime_family  TEXT    NULL CHECK (runtime_family IS NULL OR runtime_family IN (
                                'elevenlabs', 'anam', 'internal', 'ui', 'provider_webhook'
                            )),
    channel         TEXT    NULL CHECK (channel IS NULL OR channel IN (
                                'voice', 'video', 'email', 'sms', 'workflow',
                                'finance', 'ui', 'webhook'
                            )),
    trace_id        UUID    NOT NULL,
    correlation_id  UUID    NOT NULL,
    source_record_id TEXT   NULL,

    -- Thread / entity context
    session_id      UUID    NULL,
    thread_id       UUID    NULL,
    entity_type     TEXT    NULL,
    entity_id       UUID    NULL,

    -- Raw event payload (stored as-is; worker extracts domain objects)
    payload         JSONB   NOT NULL DEFAULT '{}'::jsonb,

    -- Governance fields from MemoryEventEnvelope
    risk_tier       TEXT    NOT NULL DEFAULT 'yellow'
                        CHECK (risk_tier IN ('green', 'yellow', 'red')),
    needs_approval  BOOLEAN NOT NULL DEFAULT false,
    receipt_required BOOLEAN NOT NULL DEFAULT false,

    -- Timestamps (from MemoryEventEnvelope)
    event_at            TIMESTAMPTZ NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_updated_at   TIMESTAMPTZ NULL,

    -- Idempotency: deduplicate re-delivered events within tenant+suite scope
    idempotency_key     TEXT    NOT NULL,
    CONSTRAINT uq_memory_event_inbox_idempotency
        UNIQUE (tenant_id, suite_id, idempotency_key),

    -- Queue processing state
    status          TEXT    NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'processing', 'processed', 'dead_letter')),
    attempts        INT     NOT NULL DEFAULT 0,
    last_error      TEXT    NULL,
    processed_at    TIMESTAMPTZ NULL,
    dead_lettered_at TIMESTAMPTZ NULL
);

COMMENT ON TABLE public.memory_event_inbox IS
    'Append-only intake queue for MemoryEventEnvelope payloads. '
    'Events land here; memory pipeline worker processes them into memory_objects. '
    '30-day TTL: rows with status=''processed'' and created_at < now()-30d are pruned by pg_cron. '
    'Dead-lettered rows are retained indefinitely for forensics and replay. '
    'RLS: tenant_id + suite_id + office_id scoped (Law #6).';

COMMENT ON COLUMN public.memory_event_inbox.idempotency_key IS
    'Caller-supplied dedup key. UNIQUE within (tenant_id, suite_id). '
    'Prevents duplicate processing of re-delivered events.';

-- Queue processing index (worker scans pending events ordered by arrival time)
CREATE INDEX IF NOT EXISTS idx_memory_event_inbox_queue
    ON public.memory_event_inbox (status, created_at ASC)
    WHERE status IN ('pending', 'processing');

-- Dead-letter review index
CREATE INDEX IF NOT EXISTS idx_memory_event_inbox_dead_letter
    ON public.memory_event_inbox (tenant_id, suite_id, dead_lettered_at DESC)
    WHERE status = 'dead_letter';

-- Tenant-scoped recency
CREATE INDEX IF NOT EXISTS idx_memory_event_inbox_tenant_activity
    ON public.memory_event_inbox (tenant_id, suite_id, created_at DESC);

-- RLS
ALTER TABLE public.memory_event_inbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memory_event_inbox FORCE ROW LEVEL SECURITY;

-- SELECT: tenant members see only their own events
CREATE POLICY memory_event_inbox_select_tenant ON public.memory_event_inbox
    FOR SELECT TO authenticated
    USING (app.is_member(tenant_id::text));

-- Service role bypass for worker operations
CREATE POLICY memory_event_inbox_all_service_role ON public.memory_event_inbox
    FOR ALL TO service_role
    USING (true) WITH CHECK (true);

-- INSERT: authenticated surfaces may submit events into their own tenant
CREATE POLICY memory_event_inbox_insert_tenant ON public.memory_event_inbox
    FOR INSERT TO authenticated
    WITH CHECK (
        tenant_id::text IN (
            SELECT tm.tenant_id FROM public.tenant_memberships tm
            WHERE tm.user_id = auth.uid()
        )
        AND suite_id = public.current_suite_id()
    );

-- UPDATE: allowed only for status transitions (pending → processing → processed/dead_letter)
-- Worker (service_role) handles all transitions; authenticated UPDATE is restricted.
CREATE POLICY memory_event_inbox_update_tenant ON public.memory_event_inbox
    FOR UPDATE TO authenticated
    USING (app.is_member(tenant_id::text))
    WITH CHECK (
        tenant_id::text IN (
            SELECT tm.tenant_id FROM public.tenant_memberships tm
            WHERE tm.user_id = auth.uid()
        )
    );

-- No DELETE policy — default deny under FORCE RLS

GRANT SELECT, INSERT, UPDATE ON public.memory_event_inbox TO authenticated;
GRANT ALL ON public.memory_event_inbox TO service_role;


-- =============================================================================
-- TRIGGER: memory_objects AFTER INSERT → update threads cache
-- =============================================================================
-- When a new memory_object is inserted and it references a thread,
-- update threads.latest_memory_id and threads.last_activity_at.
-- Uses service_role security context (SECURITY DEFINER) to bypass RLS on threads
-- since the trigger fires in the context of the inserting role.

CREATE OR REPLACE FUNCTION public.trg_memory_objects_update_thread_cache()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    -- Only update when the memory object is linked to a thread
    IF NEW.thread_id IS NOT NULL THEN
        UPDATE public.threads
        SET
            latest_memory_id = NEW.memory_id,
            last_activity_at = now()
        WHERE
            thread_id = NEW.thread_id
            -- Tenant safety: only update threads within the same tenant+suite
            AND tenant_id = NEW.tenant_id
            AND suite_id  = NEW.suite_id;
    END IF;

    RETURN NULL; -- AFTER trigger; return value ignored
END;
$$;

COMMENT ON FUNCTION public.trg_memory_objects_update_thread_cache() IS
    'Maintains threads.latest_memory_id and threads.last_activity_at cache. '
    'Fires AFTER INSERT on memory_objects. SECURITY DEFINER for cross-table write. '
    'Tenant safety: only updates threads within the same (tenant_id, suite_id).';

DROP TRIGGER IF EXISTS trg_memory_objects_update_thread_cache ON public.memory_objects;
CREATE TRIGGER trg_memory_objects_update_thread_cache
    AFTER INSERT ON public.memory_objects
    FOR EACH ROW EXECUTE FUNCTION public.trg_memory_objects_update_thread_cache();


-- =============================================================================
-- pg_cron: 30-day TTL pruning for processed memory_event_inbox rows
-- =============================================================================
-- Prune processed events older than 30 days. Dead-lettered events are preserved.
-- Wrapped in a DO block so it degrades gracefully if pg_cron is not available.

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_extension WHERE extname = 'pg_cron'
    ) THEN
        PERFORM cron.schedule(
            'prune_memory_event_inbox_ttl',
            '0 3 * * *',    -- daily at 03:00 UTC
            $cron$
                DELETE FROM public.memory_event_inbox
                WHERE status = 'processed'
                  AND created_at < now() - INTERVAL '30 days';
            $cron$
        );
        RAISE NOTICE 'pg_cron job ''prune_memory_event_inbox_ttl'' scheduled.';
    ELSE
        RAISE NOTICE 'pg_cron not available — memory_event_inbox TTL pruning must be run manually.';
    END IF;
END $$;
